// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SpecterOps.OktaHound.Database;

#nullable disable

namespace SpecterOps.OktaHound.Database.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260303101503_AddApplicationGroupAssignments")]
    partial class AddApplicationGroupAssignments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("SpecterOps.OktaHound.Database.CollectionStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AgentPoolsCollected")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AgentsCollected")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ApiServiceIntegrationsCollected")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ApiTokensCollected")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ApplicationsCollected")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AuthorizationServersCollected")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("BuiltinRolesCollected")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ClientSecretsCollected")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CustomRolesCollected")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DevicesCollected")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("GroupsCollected")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IdentityProvidersCollected")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("JwksCollected")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("OrganizationsCollected")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PoliciesCollected")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RealmsCollected")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ResourceSetsCollected")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RoleAssignmentsCollected")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SingletonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.Property<bool>("UsersCollected")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SingletonId")
                        .IsUnique();

                    b.ToTable("CollectionStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AgentPoolsCollected = false,
                            AgentsCollected = false,
                            ApiServiceIntegrationsCollected = false,
                            ApiTokensCollected = false,
                            ApplicationsCollected = false,
                            AuthorizationServersCollected = false,
                            BuiltinRolesCollected = false,
                            ClientSecretsCollected = false,
                            CustomRolesCollected = false,
                            DevicesCollected = false,
                            GroupsCollected = false,
                            IdentityProvidersCollected = false,
                            JwksCollected = false,
                            OrganizationsCollected = false,
                            PoliciesCollected = false,
                            RealmsCollected = false,
                            ResourceSetsCollected = false,
                            RoleAssignmentsCollected = false,
                            UsersCollected = false
                        });
                });

            modelBuilder.Entity("SpecterOps.OktaHound.Database.OktaAgent", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentPoolId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("DomainName")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("environment_name");

                    b.Property<DateTimeOffset?>("LastConnection")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OperationalStatus")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdateStatus")
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AgentPoolId");

                    b.HasIndex("DomainName");

                    b.ToTable("Agents");
                });

            modelBuilder.Entity("SpecterOps.OktaHound.Database.OktaAgentPool", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("DomainName")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("environment_name");

                    b.Property<bool>("IsActiveDirectoryAgentPool")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OperationalStatus")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DomainName");

                    b.ToTable("AgentPools");
                });

            modelBuilder.Entity("SpecterOps.OktaHound.Database.OktaApiServiceIntegration", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedById")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("DomainName")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("environment_name");

                    b.Property<string>("IntegrationType")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Permissions")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("DomainName");

                    b.ToTable("ApiServiceIntegrations");
                });

            modelBuilder.Entity("SpecterOps.OktaHound.Database.OktaApiToken", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientName")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("DomainName")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("environment_name");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NetworkConnection")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan?>("TokenWindow")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DomainName");

                    b.HasIndex("UserId");

                    b.ToTable("ApiTokens");
                });

            modelBuilder.Entity("SpecterOps.OktaHound.Database.OktaApplication", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ActiveDirectoryDomain")
                        .HasColumnType("TEXT");

                    b.Property<string>("ActiveDirectoryDomainSid")
                        .HasColumnType("TEXT");

                    b.Property<string>("ApplicationType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientType")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomProperties")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("DomainName")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("environment_name");

                    b.Property<string>("EntraClientId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntraIdDiscoveryEndpoint")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntraOnMicrosoftDomain")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntraTenantId")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Features")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("FilterGroupsByOU")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GitHubOrganizationName")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("GrantTypes")
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasRoleAssignments")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsOrgAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsService")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSuperAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JamfDomain")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OnePasswordRegionType")
                        .HasColumnType("TEXT");

                    b.Property<string>("OnePasswordSubDomain")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Permissions")
                        .HasColumnType("TEXT");

                    b.Property<string>("SignOnMode")
                        .HasColumnType("TEXT");

                    b.Property<string>("SnowflakeSubdomain")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.Property<bool>("SupportsPasswordUpdates")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SupportsSCIM")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserNameMapping")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DomainName");

                    b.HasIndex("IsService");

                    b.ToTable("Applications");
                });

            modelBuilder.Entity("SpecterOps.OktaHound.Database.OktaApplicationGrant", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ApplicationId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedById")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedByType")
                        .HasColumnType("TEXT");

                    b.Property<string>("Issuer")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<string>("ScopeId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.ToTable("ApplicationGrants");
                });

            modelBuilder.Entity("SpecterOps.OktaHound.Database.OktaApplicationGroupAssignment", b =>
                {
                    b.Property<string>("ApplicationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("GroupId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Profile")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ApplicationId", "GroupId");

                    b.HasIndex("GroupId");

                    b.ToTable("ApplicationGroupAssignments");
                });

            modelBuilder.Entity("SpecterOps.OktaHound.Database.OktaApplicationUserAssignment", b =>
                {
                    b.Property<string>("ApplicationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastSync")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("PasswordChanged")
                        .HasColumnType("TEXT");

                    b.Property<string>("Profile")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("StatusChanged")
                        .HasColumnType("TEXT");

                    b.Property<string>("SyncState")
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetUserName")
                        .HasColumnType("TEXT");

                    b.HasKey("ApplicationId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("ApplicationUserAssignments");
                });

            modelBuilder.Entity("SpecterOps.OktaHound.Database.OktaAuthorizationServer", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Audiences")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("DomainName")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("environment_name");

                    b.Property<string>("Issuer")
                        .HasColumnType("TEXT");

                    b.Property<string>("IssuerMode")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DomainName");

                    b.ToTable("AuthorizationServers");
                });

            modelBuilder.Entity("SpecterOps.OktaHound.Database.OktaBuiltinRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("DomainName")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("environment_name");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Permissions")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DomainName");

                    b.ToTable("BuiltinRoles");
                });

            modelBuilder.Entity("SpecterOps.OktaHound.Database.OktaClientSecret", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ApiServiceIntegrationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ApplicationId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("DomainName")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("environment_name");

                    b.Property<DateTimeOffset?>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ApiServiceIntegrationId");

                    b.HasIndex("ApplicationId");

                    b.HasIndex("DomainName");

                    b.ToTable("ClientSecrets");
                });

            modelBuilder.Entity("SpecterOps.OktaHound.Database.OktaCustomRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("DomainName")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("environment_name");

                    b.Property<DateTimeOffset?>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Permissions")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DomainName");

                    b.ToTable("CustomRoles");
                });

            modelBuilder.Entity("SpecterOps.OktaHound.Database.OktaDevice", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("DomainName")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("environment_name");

                    b.Property<bool?>("JailBreak")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ObjectSid")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("oktaId");

                    b.Property<string>("OsVersion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Platform")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("Registered")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResourceType")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("SecureHardwarePresent")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.Property<string>("UDID")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("udid");

                    b.HasKey("Id");

                    b.HasIndex("DomainName");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("SpecterOps.OktaHound.Database.OktaDeviceOwner", b =>
                {
                    b.Property<string>("DeviceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerId")
                        .HasColumnType("TEXT");

                    b.HasKey("DeviceId", "OwnerId");

                    b.HasIndex("OwnerId");

                    b.ToTable("DeviceOwners");
                });

            modelBuilder.Entity("SpecterOps.OktaHound.Database.OktaGroup", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("DistinguishedName")
                        .HasColumnType("TEXT");

                    b.Property<string>("DomainName")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("environment_name");

                    b.Property<string>("DomainQualifiedName")
                        .HasColumnType("TEXT");

                    b.Property<string>("DomainSid")
                        .HasColumnType("TEXT");

                    b.Property<string>("GroupScope")
                        .HasColumnType("TEXT");

                    b.Property<string>("GroupType")
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasRoleAssignments")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsOrgAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSuperAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LastMembershipUpdated")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ObjectClass")
                        .HasColumnType("TEXT");

                    b.Property<string>("ObjectGuid")
                        .HasColumnType("TEXT");

                    b.Property<string>("ObjectSid")
                        .HasColumnType("TEXT");

                    b.Property<string>("OktaGroupType")
                        .HasColumnType("TEXT");

                    b.Property<string>("SamAccountName")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceApplicationId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DomainName");

                    b.HasIndex("SourceApplicationId");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("SpecterOps.OktaHound.Database.OktaIdentityProvider", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<bool>("AutomaticUserProvisioning")
                        .HasColumnType("INTEGER")
                        .HasJsonPropertyName("autoUserProvisioning");

                    b.Property<DateTimeOffset?>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("DomainName")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("environment_name");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IssuerMode")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProtocolType")
                        .HasColumnType("TEXT");

                    b.Property<string>("TenantId")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("entraTenantId");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DomainName");

                    b.ToTable("IdentityProviders");
                });

            modelBuilder.Entity("SpecterOps.OktaHound.Database.OktaIdentityProviderGovernedGroup", b =>
                {
                    b.Property<string>("IdentityProviderId")
                        .HasColumnType("TEXT");

                    b.Property<string>("GroupId")
                        .HasColumnType("TEXT");

                    b.HasKey("IdentityProviderId", "GroupId");

                    b.HasIndex("GroupId");

                    b.ToTable("IdentityProviderGovernedGroups");
                });

            modelBuilder.Entity("SpecterOps.OktaHound.Database.OktaJWK", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ApplicationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("DomainName")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("environment_name");

                    b.Property<string>("KeyId")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("kid");

                    b.Property<string>("KeyType")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("kty");

                    b.Property<string>("KeyUsage")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("use");

                    b.Property<string>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.HasIndex("DomainName");

                    b.ToTable("JWKs");
                });

            modelBuilder.Entity("SpecterOps.OktaHound.Database.OktaOrganization", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<bool>("AgentlessDssoEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("DomainName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("environment_name");

                    b.Property<DateTimeOffset?>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.Property<string>("Subdomain")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Organizations");
                });

            modelBuilder.Entity("SpecterOps.OktaHound.Database.OktaPolicy", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("DomainName")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("environment_name");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PolicyType")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("type");

                    b.Property<int?>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("System")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DomainName");

                    b.ToTable("Policies");
                });

            modelBuilder.Entity("SpecterOps.OktaHound.Database.OktaPrivilegedUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Orn")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PrivilegedUsers");
                });

            modelBuilder.Entity("SpecterOps.OktaHound.Database.OktaRealm", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("DomainName")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("environment_name");

                    b.PrimitiveCollection<string>("Domains")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DomainName");

                    b.ToTable("Realms");
                });

            modelBuilder.Entity("SpecterOps.OktaHound.Database.OktaResourceSet", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("DomainName")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("environment_name");

                    b.Property<DateTimeOffset?>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("ResourceUris")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DomainName");

                    b.ToTable("ResourceSets");
                });

            modelBuilder.Entity("SpecterOps.OktaHound.Database.OktaRoleAssignment", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AssignmentType")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("DomainName")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("environment_name");

                    b.Property<DateTimeOffset?>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DomainName");

                    b.ToTable("RoleAssignments");
                });

            modelBuilder.Entity("SpecterOps.OktaHound.Database.OktaUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("Activated")
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasColumnType("TEXT");

                    b.Property<string>("CountryCode")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("CredentialProviderName")
                        .HasColumnType("TEXT");

                    b.Property<string>("CredentialProviderType")
                        .HasColumnType("TEXT");

                    b.Property<string>("Department")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Division")
                        .HasColumnType("TEXT");

                    b.Property<string>("DomainName")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("environment_name");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("email");

                    b.Property<string>("EmployeeNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastLogin")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Login")
                        .HasColumnType("TEXT");

                    b.Property<string>("ManagerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Organization")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalManagerId")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("managerId");

                    b.Property<DateTimeOffset?>("PasswordChanged")
                        .HasColumnType("TEXT");

                    b.Property<string>("RealmId")
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserType")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DomainName");

                    b.HasIndex("EmailAddress");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.HasIndex("ManagerId");

                    b.HasIndex("RealmId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SpecterOps.OktaHound.Database.OktaUserFactor", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("FactorType")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("VendorName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserFactors");
                });

            modelBuilder.Entity("SpecterOps.OktaHound.Database.OktaUserGroupMembership", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("GroupId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "GroupId");

                    b.HasIndex("GroupId");

                    b.ToTable("UserGroupMemberships");
                });

            modelBuilder.Entity("SpecterOps.OktaHound.Database.OktaAgent", b =>
                {
                    b.HasOne("SpecterOps.OktaHound.Database.OktaAgentPool", "AgentPool")
                        .WithMany("Agents")
                        .HasForeignKey("AgentPoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SpecterOps.OktaHound.Database.OktaOrganization", "OktaOrganization")
                        .WithMany()
                        .HasForeignKey("DomainName")
                        .HasPrincipalKey("Name")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("AgentPool");

                    b.Navigation("OktaOrganization");
                });

            modelBuilder.Entity("SpecterOps.OktaHound.Database.OktaAgentPool", b =>
                {
                    b.HasOne("SpecterOps.OktaHound.Database.OktaOrganization", "OktaOrganization")
                        .WithMany()
                        .HasForeignKey("DomainName")
                        .HasPrincipalKey("Name")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("OktaOrganization");
                });

            modelBuilder.Entity("SpecterOps.OktaHound.Database.OktaApiServiceIntegration", b =>
                {
                    b.HasOne("SpecterOps.OktaHound.Database.OktaUser", "CreatedBy")
                        .WithMany("CreatedApiServiceIntegrations")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SpecterOps.OktaHound.Database.OktaOrganization", "OktaOrganization")
                        .WithMany()
                        .HasForeignKey("DomainName")
                        .HasPrincipalKey("Name")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("CreatedBy");

                    b.Navigation("OktaOrganization");
                });

            modelBuilder.Entity("SpecterOps.OktaHound.Database.OktaApiToken", b =>
                {
                    b.HasOne("SpecterOps.OktaHound.Database.OktaOrganization", "OktaOrganization")
                        .WithMany()
                        .HasForeignKey("DomainName")
                        .HasPrincipalKey("Name")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SpecterOps.OktaHound.Database.OktaUser", "User")
                        .WithMany("ApiTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("OktaOrganization");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SpecterOps.OktaHound.Database.OktaApplication", b =>
                {
                    b.HasOne("SpecterOps.OktaHound.Database.OktaOrganization", "OktaOrganization")
                        .WithMany()
                        .HasForeignKey("DomainName")
                        .HasPrincipalKey("Name")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("OktaOrganization");
                });

            modelBuilder.Entity("SpecterOps.OktaHound.Database.OktaApplicationGrant", b =>
                {
                    b.HasOne("SpecterOps.OktaHound.Database.OktaApplication", "Application")
                        .WithMany("Grants")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Application");
                });

            modelBuilder.Entity("SpecterOps.OktaHound.Database.OktaApplicationGroupAssignment", b =>
                {
                    b.HasOne("SpecterOps.OktaHound.Database.OktaApplication", "Application")
                        .WithMany()
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SpecterOps.OktaHound.Database.OktaGroup", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Application");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("SpecterOps.OktaHound.Database.OktaApplicationUserAssignment", b =>
                {
                    b.HasOne("SpecterOps.OktaHound.Database.OktaApplication", "Application")
                        .WithMany()
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SpecterOps.OktaHound.Database.OktaUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Application");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SpecterOps.OktaHound.Database.OktaAuthorizationServer", b =>
                {
                    b.HasOne("SpecterOps.OktaHound.Database.OktaOrganization", "OktaOrganization")
                        .WithMany()
                        .HasForeignKey("DomainName")
                        .HasPrincipalKey("Name")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("OktaOrganization");
                });

            modelBuilder.Entity("SpecterOps.OktaHound.Database.OktaBuiltinRole", b =>
                {
                    b.HasOne("SpecterOps.OktaHound.Database.OktaOrganization", "OktaOrganization")
                        .WithMany()
                        .HasForeignKey("DomainName")
                        .HasPrincipalKey("Name")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("OktaOrganization");
                });

            modelBuilder.Entity("SpecterOps.OktaHound.Database.OktaClientSecret", b =>
                {
                    b.HasOne("SpecterOps.OktaHound.Database.OktaApiServiceIntegration", "ApiServiceIntegration")
                        .WithMany("ClientSecrets")
                        .HasForeignKey("ApiServiceIntegrationId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SpecterOps.OktaHound.Database.OktaApplication", "Application")
                        .WithMany("ClientSecrets")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SpecterOps.OktaHound.Database.OktaOrganization", "OktaOrganization")
                        .WithMany()
                        .HasForeignKey("DomainName")
                        .HasPrincipalKey("Name")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("ApiServiceIntegration");

                    b.Navigation("Application");

                    b.Navigation("OktaOrganization");
                });

            modelBuilder.Entity("SpecterOps.OktaHound.Database.OktaCustomRole", b =>
                {
                    b.HasOne("SpecterOps.OktaHound.Database.OktaOrganization", "OktaOrganization")
                        .WithMany()
                        .HasForeignKey("DomainName")
                        .HasPrincipalKey("Name")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("OktaOrganization");
                });

            modelBuilder.Entity("SpecterOps.OktaHound.Database.OktaDevice", b =>
                {
                    b.HasOne("SpecterOps.OktaHound.Database.OktaOrganization", "OktaOrganization")
                        .WithMany()
                        .HasForeignKey("DomainName")
                        .HasPrincipalKey("Name")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("OktaOrganization");
                });

            modelBuilder.Entity("SpecterOps.OktaHound.Database.OktaDeviceOwner", b =>
                {
                    b.HasOne("SpecterOps.OktaHound.Database.OktaDevice", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SpecterOps.OktaHound.Database.OktaUser", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Device");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("SpecterOps.OktaHound.Database.OktaGroup", b =>
                {
                    b.HasOne("SpecterOps.OktaHound.Database.OktaOrganization", "OktaOrganization")
                        .WithMany()
                        .HasForeignKey("DomainName")
                        .HasPrincipalKey("Name")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SpecterOps.OktaHound.Database.OktaApplication", "SourceApplication")
                        .WithMany("ImportedGroups")
                        .HasForeignKey("SourceApplicationId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("OktaOrganization");

                    b.Navigation("SourceApplication");
                });

            modelBuilder.Entity("SpecterOps.OktaHound.Database.OktaIdentityProvider", b =>
                {
                    b.HasOne("SpecterOps.OktaHound.Database.OktaOrganization", "OktaOrganization")
                        .WithMany()
                        .HasForeignKey("DomainName")
                        .HasPrincipalKey("Name")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("OktaOrganization");
                });

            modelBuilder.Entity("SpecterOps.OktaHound.Database.OktaIdentityProviderGovernedGroup", b =>
                {
                    b.HasOne("SpecterOps.OktaHound.Database.OktaGroup", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SpecterOps.OktaHound.Database.OktaIdentityProvider", "IdentityProvider")
                        .WithMany()
                        .HasForeignKey("IdentityProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("IdentityProvider");
                });

            modelBuilder.Entity("SpecterOps.OktaHound.Database.OktaJWK", b =>
                {
                    b.HasOne("SpecterOps.OktaHound.Database.OktaApplication", "Application")
                        .WithMany("JWKs")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SpecterOps.OktaHound.Database.OktaOrganization", "OktaOrganization")
                        .WithMany()
                        .HasForeignKey("DomainName")
                        .HasPrincipalKey("Name")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Application");

                    b.Navigation("OktaOrganization");
                });

            modelBuilder.Entity("SpecterOps.OktaHound.Database.OktaPolicy", b =>
                {
                    b.HasOne("SpecterOps.OktaHound.Database.OktaOrganization", "OktaOrganization")
                        .WithMany()
                        .HasForeignKey("DomainName")
                        .HasPrincipalKey("Name")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("OktaOrganization");
                });

            modelBuilder.Entity("SpecterOps.OktaHound.Database.OktaPrivilegedUser", b =>
                {
                    b.HasOne("SpecterOps.OktaHound.Database.OktaUser", "User")
                        .WithMany()
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SpecterOps.OktaHound.Database.OktaRealm", b =>
                {
                    b.HasOne("SpecterOps.OktaHound.Database.OktaOrganization", "OktaOrganization")
                        .WithMany()
                        .HasForeignKey("DomainName")
                        .HasPrincipalKey("Name")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("OktaOrganization");
                });

            modelBuilder.Entity("SpecterOps.OktaHound.Database.OktaResourceSet", b =>
                {
                    b.HasOne("SpecterOps.OktaHound.Database.OktaOrganization", "OktaOrganization")
                        .WithMany()
                        .HasForeignKey("DomainName")
                        .HasPrincipalKey("Name")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("OktaOrganization");
                });

            modelBuilder.Entity("SpecterOps.OktaHound.Database.OktaRoleAssignment", b =>
                {
                    b.HasOne("SpecterOps.OktaHound.Database.OktaOrganization", "OktaOrganization")
                        .WithMany()
                        .HasForeignKey("DomainName")
                        .HasPrincipalKey("Name")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("OktaOrganization");
                });

            modelBuilder.Entity("SpecterOps.OktaHound.Database.OktaUser", b =>
                {
                    b.HasOne("SpecterOps.OktaHound.Database.OktaOrganization", "OktaOrganization")
                        .WithMany()
                        .HasForeignKey("DomainName")
                        .HasPrincipalKey("Name")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SpecterOps.OktaHound.Database.OktaUser", "Manager")
                        .WithMany("DirectReports")
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SpecterOps.OktaHound.Database.OktaRealm", "Realm")
                        .WithMany("Users")
                        .HasForeignKey("RealmId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Manager");

                    b.Navigation("OktaOrganization");

                    b.Navigation("Realm");
                });

            modelBuilder.Entity("SpecterOps.OktaHound.Database.OktaUserFactor", b =>
                {
                    b.HasOne("SpecterOps.OktaHound.Database.OktaUser", "User")
                        .WithMany("AuthenticationFactors")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("User");
                });

            modelBuilder.Entity("SpecterOps.OktaHound.Database.OktaUserGroupMembership", b =>
                {
                    b.HasOne("SpecterOps.OktaHound.Database.OktaGroup", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SpecterOps.OktaHound.Database.OktaUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SpecterOps.OktaHound.Database.OktaAgentPool", b =>
                {
                    b.Navigation("Agents");
                });

            modelBuilder.Entity("SpecterOps.OktaHound.Database.OktaApiServiceIntegration", b =>
                {
                    b.Navigation("ClientSecrets");
                });

            modelBuilder.Entity("SpecterOps.OktaHound.Database.OktaApplication", b =>
                {
                    b.Navigation("ClientSecrets");

                    b.Navigation("Grants");

                    b.Navigation("ImportedGroups");

                    b.Navigation("JWKs");
                });

            modelBuilder.Entity("SpecterOps.OktaHound.Database.OktaRealm", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("SpecterOps.OktaHound.Database.OktaUser", b =>
                {
                    b.Navigation("ApiTokens");

                    b.Navigation("AuthenticationFactors");

                    b.Navigation("CreatedApiServiceIntegrations");

                    b.Navigation("DirectReports");
                });
#pragma warning restore 612, 618
        }
    }
}
