<#
.SYNOPSIS
    Converts a BloodHound extension file into markdown (*.md).
.NOTES
    Version: 2.0
#>

#Requires -Version 5.1

[CmdletBinding()]
param (
    [Parameter(Mandatory = $false)]
    [ValidateNotNullOrEmpty()]
    [string] $InputPath = (Join-Path -Path $PSScriptRoot -ChildPath '../Src/Extensions/bhce-okta-extension.json'),

    [Parameter(Mandatory = $false)]
    [ValidateNotNullOrEmpty()]
    [string] $OutputPath = (Join-Path -Path $PSScriptRoot -ChildPath '../Documentation/Schema.md'),

    [Parameter(Mandatory = $false)]
    [AllowNull()]
    [string] $NodeLinkBasePath = 'NodeDescriptions',

    [Parameter(Mandatory = $false)]
    [AllowNull()]
    [string] $EdgeLinkBasePath = 'EdgeDescriptions'
)

Set-StrictMode -Version Latest

function Get-KindMarkdownLink {
    [CmdletBinding()]
    [OutputType([string])]
    param (
        [Parameter(Mandatory = $true)]
        [ValidateNotNullOrEmpty()]
        [string] $KindName,

        [Parameter(Mandatory = $false)]
        [AllowNull()]
        [string] $LinkBasePath
    )

    if ($null -eq $LinkBasePath) {
        return $KindName
    } elseif ([string]::Empty -eq $LinkBasePath) {
        return '[{0}]({0}.md)' -f $KindName
    } else {
        return '[{0}]({1}/{0}.md)' -f $KindName, $LinkBasePath
    }
}

# Parse the JSON file
[psobject] $json = Get-Content -Path $InputPath | ConvertFrom-Json
[psobject[]] $nodeKinds = @($json.node_kinds | Sort-Object -Property name)
[psobject[]] $relationshipKinds = @($json.relationship_kinds | Sort-Object -Property name)
[string] $schemaDisplayName = if (-not [string]::IsNullOrWhiteSpace($json.schema.display_name)) {
    $json.schema.display_name
} else {
    $json.schema.name
}

# Generate the header and metadata section
[string] $markdown = @'
# OktaHound Extension Schema

## Metadata

**Name:** {0}<br>
**Display Name:** {1}<br>
**Version:** {2}<br>
**Namespace:** {3}<br>
**Environment Kind:** {4}<br>
**Source Kind:** {5}

'@ -f $json.schema.name, $schemaDisplayName, $json.schema.version, $json.schema.namespace, $json.environments[0].environment_kind, $json.environments[0].source_kind

$markdown += @'

## Nodes

| Icon | Node Kind | Display Name |
|------|-----------|--------------|
'@

# Add a table row for each node kind
foreach ($nodeKind in $nodeKinds) {
    # Append node-specific markdown
    # Sample: | ![Okta_Organization](Icons/Okta_Organization.png) | Okta_Organization | Okta Organization |
    $markdown += "`n"
    [string] $nodeKindDisplay = Get-KindMarkdownLink -KindName $nodeKind.name -LinkBasePath $NodeLinkBasePath
    $markdown += '| ![{0}](Icons/{0}.png) | {1} | {2} |' -f $nodeKind.name, $nodeKindDisplay, $nodeKind.display_name
}

$markdown += "`n`n"
$markdown += @'
## Edges

| Relationship Kind | Traversable | Description |
|-------------------|:-----------:|-------------|
'@

# Add a table row for each relationship kind
foreach ($relationshipKind in $relationshipKinds) {
    # Append relationship-specific markdown
    # Sample: | OktaUserHasRole | ✅ | Indicates that a user is assigned a role in Okta. |
    $markdown += "`n"
    [string] $traversableIcon = if ($relationshipKind.is_traversable) { '✅' } else { '❌' }
    [string] $relationshipKindDisplay = Get-KindMarkdownLink -KindName $relationshipKind.name -LinkBasePath $EdgeLinkBasePath
    $markdown += '| {0} | {1} | {2} |' -f $relationshipKindDisplay, $traversableIcon, $relationshipKind.description
}

# Add footer note
$markdown += "`n`n"
$markdown += @'
> [!NOTE]
> This file is automatically generated from the [bhce-okta-extension.json](../Src/Extensions/bhce-okta-extension.json) file
> that is bundled with OktaHound Community Edition.
'@

# Normalize line endings to CRLF for Git working tree
$markdown = $markdown -replace "`r?`n", "`r`n"

# Create the Nodes.md file
Set-Content -Path $OutputPath -Value $markdown -Encoding UTF8 -Verbose
