<#
.SYNOPSIS
    Converts custom Cypher query files (*.json) into markdown (*.md) or MDX.
#>

#Requires -Version 5.1

[CmdletBinding()]
param (
    [Parameter(Mandatory = $false)]
    [ValidateNotNullOrEmpty()]
    [string] $InputDirectory = (Join-Path -Path $PSScriptRoot -ChildPath '../Src/Queries/'),

    [Parameter(Mandatory = $false)]
    [ValidateNotNullOrEmpty()]
    [string] $OutputFilePath = (Join-Path -Path $PSScriptRoot -ChildPath '../Documentation/Queries.md'),

    [Parameter(Mandatory = $false)]
    [ValidateNotNullOrEmpty()]
    [string] $QueriesPath = '../Src/Queries',

    [Parameter(Mandatory = $false)]
    [switch] $OfficialDocs
)

Set-StrictMode -Version Latest

[string] $markdown = ''
if ($OfficialDocs) {
    $markdown += @'
---
title: Cypher Queries
description: Default Cypher queries for the OktaHound extension
icon: code
---

<img noZoom src="/assets/enterprise-AND-community-edition-pill-tag.svg" alt="Applies to BloodHound Enterprise and CE"/>

'@
} else {
    $markdown += @'
# Cypher Queries

'@
}

$markdown += @'
The following custom Cypher queries can be imported into BloodHound to enhance Okta visibility.
Each query is defined in a JSON file located in the [Queries]({0}) directory of the OktaHound repository.

'@ -f $QueriesPath

if ($OfficialDocs) {
    $markdown += @'
<Info>
This file is automatically generated from the [JSON query files]({0})
that are bundled with the `OktaHound` collector.
</Info>

'@ -f $QueriesPath
} else {
    $markdown += @'
> [!NOTE]
> This file is automatically generated from the [JSON query files]({0})
> that are bundled with the `OktaHound` collector.

'@ -f $QueriesPath
}

Get-ChildItem -File -Path $InputDirectory -Filter '*.json' | Sort-Object -Property Name | ForEach-Object {
    # Parse the JSON content of the cypher query file
    [psobject] $json = Get-Content -Path $PSItem.FullName | ConvertFrom-Json

    # Remove 'Okta: ' prefix from title for cleaner headings
    [string] $title = $json.Name -replace 'Okta: '

    # Sanitize line breaks in description and query
    [string] $description = $json.Description -replace '\n',"`n"
    [string] $query = $json.Query -replace '\n',"`n"

    [string] $fileName = $PSItem.Name

    # Append file-specific markdown
    $markdown += @'

## {0}

{1}

```cypher
{2}
```

This query can be imported into BloodHound from the [{3}]({4}/{3}) file.

'@ -f $title, $description, $query, $fileName, $QueriesPath
}

# Normalize line endings to CRLF for Git working tree
$markdown = $markdown -replace "`r?`n", "`r`n"

Set-Content -Path $OutputFilePath -Value $markdown -Encoding UTF8 -Verbose
