<#
.SYNOPSIS
    Converts custom cypher query files (*.json) into markdown (*.md).
#>

#Requires -Version 5.1

[CmdletBinding()]
param (
    [Parameter(Mandatory = $false)]
    [ValidateNotNullOrEmpty()]
    [string] $InputDirectory = (Join-Path -Path $PSScriptRoot -ChildPath '../Src/Queries/'),

    [Parameter(Mandatory = $false)]
    [ValidateNotNullOrEmpty()]
    [string] $OutputFilePath = (Join-Path -Path $PSScriptRoot -ChildPath '../Documentation/Queries.md')
)

Set-StrictMode -Version Latest

[string] $markdown = @'
# Custom BloodHound Queries for Okta

The following custom Cypher queries can be imported into BloodHound to enhance Okta visibility.
Each query is defined in a JSON file located in the [Queries](https://github.com/SpecterOps/OktaHound/tree/main/Src/Queries) directory of the OktaHound repository.

> [!NOTE]
> This file is automatically generated from the [JSON query files](https://github.com/SpecterOps/OktaHound/tree/main/Src/Queries)
> that are bundled with the `OktaHound` collector.

'@

Get-ChildItem -File -Path $InputDirectory -Filter '*.json' | Sort-Object -Property Name | ForEach-Object {
    # Parse the JSON content of the cypher query file
    [psobject] $json = Get-Content -Path $PSItem.FullName | ConvertFrom-Json

    # Remove 'Okta: ' prefix from title for cleaner headings
    [string] $title = $json.Name -replace 'Okta: '

    # Sanitize line breaks in description and query
    [string] $description = $json.Description -replace '\n',"`n"
    [string] $query = $json.Query -replace '\n',"`n"

    [string] $fileName = $PSItem.Name

    # Append file-specific markdown
    $markdown += @'

## {0}

{1}

```cypher
{2}
```

This query can be imported into BloodHound from the [{3}](https://github.com/SpecterOps/OktaHound/tree/main/Src/Queries/{3}) file.

'@ -f $title, $description, $query, $fileName
}

# Normalize line endings to CRLF for Git working tree
$markdown = $markdown -replace "`r?`n", "`r`n"

Set-Content -Path $OutputFilePath -Value $markdown -Encoding UTF8 -Verbose
