<#
.SYNOPSIS
    Converts a BloodHound extension file into markdown (*.md).
#>

#Requires -Version 5.1

[CmdletBinding()]
param (
    [Parameter(Mandatory = $false)]
    [ValidateNotNullOrEmpty()]
    [string] $InputPath = (Join-Path -Path $PSScriptRoot -ChildPath '../Src/Extensions/bhce-okta-extension.json'),

    [Parameter(Mandatory = $false)]
    [ValidateNotNullOrEmpty()]
    [string] $OutputPath = (Join-Path -Path $PSScriptRoot -ChildPath '../Documentation/Schema.md')
)

Set-StrictMode -Version Latest

[string] $markdown = @'
# OktaHound Extension Schema

## Nodes

| Icon | Node Kind | Display Name |
|------|-----------|--------------|
'@

# Parse the JSON file
[psobject] $json = Get-Content -Path $InputPath | ConvertFrom-Json
[psobject[]] $nodeKinds = @($json.node_kinds | Sort-Object -Property name)
[psobject[]] $relationshipKinds = @($json.relationship_kinds | Sort-Object -Property name)

# Add a table row for each node kind
foreach ($nodeKind in $nodeKinds) {
    # Append node-specific markdown
    # Sample: | ![Okta_Organization](Icons/Okta_Organization.png) | Okta_Organization | Okta Organization |
    $markdown += "`n"
    $markdown += '| ![{0}](Icons/{0}.png) | {0} | {1} |' -f $nodeKind.name, $nodeKind.display_name
}

$markdown += "`n`n"
$markdown += @'
## Edges

| Relationship Kind | Traversable | Description |
|-------------------|:-----------:|-------------|
'@

# Add a table row for each relationship kind
foreach ($relationshipKind in $relationshipKinds) {
    # Append relationship-specific markdown
    # Sample: | OktaUserHasRole | ✅ | Indicates that a user is assigned a role in Okta. |
    $markdown += "`n"
    [string] $traversableIcon = if ($relationshipKind.is_traversable) { '✅' } else { '❌' }
    $markdown += '| {0} | {1} | {2} |' -f $relationshipKind.name, $traversableIcon, $relationshipKind.description
}

# Add footer note
$markdown += "`n`n"
$markdown += @'
> [!NOTE]
> This file is automatically generated from the [bhce-okta-extension.json](../Src/Extensions/bhce-okta-extension.json) file
> that is bundled with OktaHound Community Edition.
'@

# Normalize line endings to CRLF for Git working tree
$markdown = $markdown -replace "`r?`n", "`r`n"

# Create the Nodes.md file
Set-Content -Path $OutputPath -Value $markdown -Encoding UTF8 -Verbose
